### ISSUE TITLE
MC_USE_PILL should pass PillColor

### ISSUE THREAD

**Issue by Xalum** [Meowlala/RepentanceAPIIssueTracker#451] opened 2022-03-01 03:17 UTC
There is currently no other way to accurately determine whether the pill currently being used is a Horse Pill, while maintaining compatibility with Echo Chamber

**Comment by laceous** [comment] 2022-10-12 10:37
This would also be useful for custom gold pill handling.

**Comment by Zamiell** [comment] 2023-02-27 21:11
duplicate of #275, please close

**Closed as not planned** 2023-11-24 17:08 UTC
Labels: duplicate
