### ISSUE TITLE
TrinketType.TRINKET_FIRECRACKER and TrinketType.TRINKET_GIANT_BEAN were not kept as legacy variables

### ISSUE THREAD

**Issue by AgentCucco** [Meowlala/RepentanceAPIIssueTracker#352] opened 2021-11-11 15:18 UTC
Any mods that used the old variable names will be broken until they get updated (if they do). Not sure as to why they weren't added like the old ab+ enums which were kept for compatibility purposes.

**Comment by UnderscoreKilburn** [comment] 2021-11-11 15:22
Because I forgot, whoops

**Comment by Meowlala** [comment] 2021-11-17 16:56
Confirmed fixed in 1.7.6

**Closed by Meowlala** 2021-11-17 16:56 UTC
Labels: bug, lua, fixed in patch
