### ISSUE TITLE
The Isaac.CountEntities() function is completely broken and returns arbitrary Lua data, after the first repentance API patch.

### ISSUE THREAD

**Issue by DarkestSentinel** [Meowlala/RepentanceAPIIssueTracker#106] opened 2021-05-15 10:24 UTC
Can cause errors for mods which don't handle nil values there since it was 0 before. Returning 0 also made more sense in my opinion

**Comment by minichibis** [comment] 2021-05-15 17:00
I've been tinkering with it in the context of honeydrop and it has been returning some bizzare values.

0 beeters: nil
1 beeter: -1
2 beeters: 180
3 beeters: 160
4 beeters: nil
5 beeters: function 0052DA40
6 beeters: 0.66

It seems to be returning completely arbitrary values from nearby code snippets, or something?

**Comment by Meowlala** [comment] 2021-05-15 17:01
Yeah, it's a lot worse than this. `Isaac.CountEntities` is completely broken, it returns N values, with N being equal to the number of entities it finds. It looks like it's returning the Lua stack in a completely messed up fashion.

**Comment by Meowlala** [comment] 2021-11-11 00:54
Confirmed fixed in 1.7.5.

**Closed by Meowlala** 2021-11-11 00:54 UTC
Labels: bug, lua, repentance, fixed in patch, high priority
