### ISSUE TITLE
Entity.SpawnerEntity is nil even when SpawnerType and SpawnerVariant are set

### ISSUE THREAD

**Issue by DarkestSentinel** [Meowlala/RepentanceAPIIssueTracker#42] opened 2021-05-05 08:09 UTC
Entity.SpawnerType and Entity.SpawnerVariant work as intended and show the .Type and .Variant of the spawner of that entity, if that entity indeed has a spawner. It's odd for Entity.SpawnerEntity to be nil in that case.

**Comment by Meowlala** [comment] 2021-05-05 12:15
Not always nil, but sometimes nil even when SpawnerType and SpawnerVariant are set.

**Comment by Meowlala** [comment] 2021-05-15 05:03
I haven't been able to verify that this is fixed in the first rep API patch because I don't know how to reproduce it, but I'll close this for now unless it is found to be an issue again.

**Closed by Meowlala** 2021-05-15 05:03 UTC
Labels: bug, fixed in patch, lua
