### ISSUE TITLE
NpcState.STATE_DEATH and NpcState.STATE_UNIQUE_DEATH are reversed in enums.lua

### ISSUE THREAD

**Issue by TaigaTreant** [Meowlala/RepentanceAPIIssueTracker#337] opened 2021-11-01 02:34 UTC
NpcState 17 (NpcState.STATE_DEATH at the time of writing) has some unique properties regardless of entity type; when set the enemy with the state will be removed as soon as their current animation finishes playing, regardless of whether or not the entity has actually been killed. This seems like the behavior that should be associated with NpcState.STATE_UNIQUE_DEATH (NpcState 16 at the time of writing), and may suggest that the names of the two states in enums.lua is currently swapped.

**Comment by UnderscoreKilburn** [comment] 2021-11-02 00:19
Turns out there was a missing STATE_ATTACK5 enum, meaning that every value after STATE_ATTACK4 was incorrect. STATE_DEATH should be 18, while STATE_UNIQUE_DEATH should be 17.

**Comment by Meowlala** [comment] 2021-11-11 00:48
Confirmed fixed in 1.7.5.

**Closed by Meowlala** 2021-11-11 00:48 UTC
Labels: bug, lua, fixed in patch
